/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedirectRouteImport } from './routes/redirect'
import { Route as JoinRouteImport } from './routes/join'
import { Route as DeferredRouteImport } from './routes/deferred'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout'
import { Route as UsersRouteRouteImport } from './routes/users.route'
import { Route as PostsRouteRouteImport } from './routes/posts.route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as UsersIndexRouteImport } from './routes/users.index'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as UsersUserIdRouteImport } from './routes/users.$userId'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as PathlessLayoutNestedLayoutRouteImport } from './routes/_pathlessLayout/_nested-layout'
import { Route as AuthLoginRouteRouteImport } from './routes/_auth/login/route'
import { Route as AppOrganizationIndexRouteImport } from './routes/_app/$organization/index'
import { Route as PostsPostIdDeepRouteImport } from './routes/posts_.$postId.deep'
import { Route as ApiUsersIdRouteImport } from './routes/api/users.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PathlessLayoutNestedLayoutRouteBRouteImport } from './routes/_pathlessLayout/_nested-layout/route-b'
import { Route as PathlessLayoutNestedLayoutRouteARouteImport } from './routes/_pathlessLayout/_nested-layout/route-a'
import { Route as AppOrganizationNewTeamRouteImport } from './routes/_app/$organization/new-team'
import { Route as AppOrganizationIssuesRouteImport } from './routes/_app/$organization/issues'
import { Route as AppOrganizationInboxRouteImport } from './routes/_app/$organization/inbox'
import { Route as AppOrganizationViewsIndexRouteImport } from './routes/_app/$organization/views/index'
import { Route as AppOrganizationProjectsIndexRouteImport } from './routes/_app/$organization/projects/index'
import { Route as AppOrganizationViewsIssuesRouteImport } from './routes/_app/$organization/views/issues'
import { Route as AppOrganizationProjectsAllRouteImport } from './routes/_app/$organization/projects/all'

const RedirectRoute = RedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const DeferredRoute = DeferredRouteImport.update({
  id: '/deferred',
  path: '/deferred',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRouteRoute = UsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRouteRoute = PostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRouteRoute,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => UsersRouteRoute,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRouteRoute,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutNestedLayoutRoute =
  PathlessLayoutNestedLayoutRouteImport.update({
    id: '/_nested-layout',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const AuthLoginRouteRoute = AuthLoginRouteRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrganizationIndexRoute = AppOrganizationIndexRouteImport.update({
  id: '/$organization/',
  path: '/$organization/',
  getParentRoute: () => AppRouteRoute,
} as any)
const PostsPostIdDeepRoute = PostsPostIdDeepRouteImport.update({
  id: '/posts_/$postId/deep',
  path: '/posts/$postId/deep',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersIdRoute = ApiUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiUsersRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutNestedLayoutRouteBRoute =
  PathlessLayoutNestedLayoutRouteBRouteImport.update({
    id: '/route-b',
    path: '/route-b',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)
const PathlessLayoutNestedLayoutRouteARoute =
  PathlessLayoutNestedLayoutRouteARouteImport.update({
    id: '/route-a',
    path: '/route-a',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)
const AppOrganizationNewTeamRoute = AppOrganizationNewTeamRouteImport.update({
  id: '/$organization/new-team',
  path: '/$organization/new-team',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrganizationIssuesRoute = AppOrganizationIssuesRouteImport.update({
  id: '/$organization/issues',
  path: '/$organization/issues',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrganizationInboxRoute = AppOrganizationInboxRouteImport.update({
  id: '/$organization/inbox',
  path: '/$organization/inbox',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrganizationViewsIndexRoute =
  AppOrganizationViewsIndexRouteImport.update({
    id: '/$organization/views/',
    path: '/$organization/views/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppOrganizationProjectsIndexRoute =
  AppOrganizationProjectsIndexRouteImport.update({
    id: '/$organization/projects/',
    path: '/$organization/projects/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppOrganizationViewsIssuesRoute =
  AppOrganizationViewsIssuesRouteImport.update({
    id: '/$organization/views/issues',
    path: '/$organization/views/issues',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppOrganizationProjectsAllRoute =
  AppOrganizationProjectsAllRouteImport.update({
    id: '/$organization/projects/all',
    path: '/$organization/projects/all',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/posts': typeof PostsRouteRouteWithChildren
  '/users': typeof UsersRouteRouteWithChildren
  '/deferred': typeof DeferredRoute
  '/join': typeof JoinRoute
  '/redirect': typeof RedirectRoute
  '/login': typeof AuthLoginRouteRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/': typeof AppIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/$organization/inbox': typeof AppOrganizationInboxRoute
  '/$organization/issues': typeof AppOrganizationIssuesRoute
  '/$organization/new-team': typeof AppOrganizationNewTeamRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/posts/$postId/deep': typeof PostsPostIdDeepRoute
  '/$organization': typeof AppOrganizationIndexRoute
  '/$organization/projects/all': typeof AppOrganizationProjectsAllRoute
  '/$organization/views/issues': typeof AppOrganizationViewsIssuesRoute
  '/$organization/projects': typeof AppOrganizationProjectsIndexRoute
  '/$organization/views': typeof AppOrganizationViewsIndexRoute
}
export interface FileRoutesByTo {
  '/deferred': typeof DeferredRoute
  '/join': typeof JoinRoute
  '/redirect': typeof RedirectRoute
  '/login': typeof AuthLoginRouteRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/': typeof AppIndexRoute
  '/posts': typeof PostsIndexRoute
  '/users': typeof UsersIndexRoute
  '/$organization/inbox': typeof AppOrganizationInboxRoute
  '/$organization/issues': typeof AppOrganizationIssuesRoute
  '/$organization/new-team': typeof AppOrganizationNewTeamRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/posts/$postId/deep': typeof PostsPostIdDeepRoute
  '/$organization': typeof AppOrganizationIndexRoute
  '/$organization/projects/all': typeof AppOrganizationProjectsAllRoute
  '/$organization/views/issues': typeof AppOrganizationViewsIssuesRoute
  '/$organization/projects': typeof AppOrganizationProjectsIndexRoute
  '/$organization/views': typeof AppOrganizationViewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/posts': typeof PostsRouteRouteWithChildren
  '/users': typeof UsersRouteRouteWithChildren
  '/_pathlessLayout': typeof PathlessLayoutRouteWithChildren
  '/deferred': typeof DeferredRoute
  '/join': typeof JoinRoute
  '/redirect': typeof RedirectRoute
  '/_auth/login': typeof AuthLoginRouteRoute
  '/_pathlessLayout/_nested-layout': typeof PathlessLayoutNestedLayoutRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/_app/': typeof AppIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/_app/$organization/inbox': typeof AppOrganizationInboxRoute
  '/_app/$organization/issues': typeof AppOrganizationIssuesRoute
  '/_app/$organization/new-team': typeof AppOrganizationNewTeamRoute
  '/_pathlessLayout/_nested-layout/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/_pathlessLayout/_nested-layout/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/posts_/$postId/deep': typeof PostsPostIdDeepRoute
  '/_app/$organization/': typeof AppOrganizationIndexRoute
  '/_app/$organization/projects/all': typeof AppOrganizationProjectsAllRoute
  '/_app/$organization/views/issues': typeof AppOrganizationViewsIssuesRoute
  '/_app/$organization/projects/': typeof AppOrganizationProjectsIndexRoute
  '/_app/$organization/views/': typeof AppOrganizationViewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/posts'
    | '/users'
    | '/deferred'
    | '/join'
    | '/redirect'
    | '/login'
    | '/api/users'
    | '/posts/$postId'
    | '/users/$userId'
    | '/'
    | '/posts/'
    | '/users/'
    | '/$organization/inbox'
    | '/$organization/issues'
    | '/$organization/new-team'
    | '/route-a'
    | '/route-b'
    | '/api/auth/$'
    | '/api/users/$id'
    | '/posts/$postId/deep'
    | '/$organization'
    | '/$organization/projects/all'
    | '/$organization/views/issues'
    | '/$organization/projects'
    | '/$organization/views'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/deferred'
    | '/join'
    | '/redirect'
    | '/login'
    | '/api/users'
    | '/posts/$postId'
    | '/users/$userId'
    | '/'
    | '/posts'
    | '/users'
    | '/$organization/inbox'
    | '/$organization/issues'
    | '/$organization/new-team'
    | '/route-a'
    | '/route-b'
    | '/api/auth/$'
    | '/api/users/$id'
    | '/posts/$postId/deep'
    | '/$organization'
    | '/$organization/projects/all'
    | '/$organization/views/issues'
    | '/$organization/projects'
    | '/$organization/views'
  id:
    | '__root__'
    | '/_app'
    | '/posts'
    | '/users'
    | '/_pathlessLayout'
    | '/deferred'
    | '/join'
    | '/redirect'
    | '/_auth/login'
    | '/_pathlessLayout/_nested-layout'
    | '/api/users'
    | '/posts/$postId'
    | '/users/$userId'
    | '/_app/'
    | '/posts/'
    | '/users/'
    | '/_app/$organization/inbox'
    | '/_app/$organization/issues'
    | '/_app/$organization/new-team'
    | '/_pathlessLayout/_nested-layout/route-a'
    | '/_pathlessLayout/_nested-layout/route-b'
    | '/api/auth/$'
    | '/api/users/$id'
    | '/posts_/$postId/deep'
    | '/_app/$organization/'
    | '/_app/$organization/projects/all'
    | '/_app/$organization/views/issues'
    | '/_app/$organization/projects/'
    | '/_app/$organization/views/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  PostsRouteRoute: typeof PostsRouteRouteWithChildren
  UsersRouteRoute: typeof UsersRouteRouteWithChildren
  PathlessLayoutRoute: typeof PathlessLayoutRouteWithChildren
  DeferredRoute: typeof DeferredRoute
  JoinRoute: typeof JoinRoute
  RedirectRoute: typeof RedirectRoute
  AuthLoginRouteRoute: typeof AuthLoginRouteRoute
  ApiUsersRoute: typeof ApiUsersRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  PostsPostIdDeepRoute: typeof PostsPostIdDeepRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deferred': {
      id: '/deferred'
      path: '/deferred'
      fullPath: '/deferred'
      preLoaderRoute: typeof DeferredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof UsersRouteRoute
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof UsersRouteRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/_nested-layout': {
      id: '/_pathlessLayout/_nested-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$organization/': {
      id: '/_app/$organization/'
      path: '/$organization'
      fullPath: '/$organization'
      preLoaderRoute: typeof AppOrganizationIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/posts_/$postId/deep': {
      id: '/posts_/$postId/deep'
      path: '/posts/$postId/deep'
      fullPath: '/posts/$postId/deep'
      preLoaderRoute: typeof PostsPostIdDeepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/$id': {
      id: '/api/users/$id'
      path: '/$id'
      fullPath: '/api/users/$id'
      preLoaderRoute: typeof ApiUsersIdRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/_nested-layout/route-b': {
      id: '/_pathlessLayout/_nested-layout/route-b'
      path: '/route-b'
      fullPath: '/route-b'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteBRouteImport
      parentRoute: typeof PathlessLayoutNestedLayoutRoute
    }
    '/_pathlessLayout/_nested-layout/route-a': {
      id: '/_pathlessLayout/_nested-layout/route-a'
      path: '/route-a'
      fullPath: '/route-a'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteARouteImport
      parentRoute: typeof PathlessLayoutNestedLayoutRoute
    }
    '/_app/$organization/new-team': {
      id: '/_app/$organization/new-team'
      path: '/$organization/new-team'
      fullPath: '/$organization/new-team'
      preLoaderRoute: typeof AppOrganizationNewTeamRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/$organization/issues': {
      id: '/_app/$organization/issues'
      path: '/$organization/issues'
      fullPath: '/$organization/issues'
      preLoaderRoute: typeof AppOrganizationIssuesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/$organization/inbox': {
      id: '/_app/$organization/inbox'
      path: '/$organization/inbox'
      fullPath: '/$organization/inbox'
      preLoaderRoute: typeof AppOrganizationInboxRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/$organization/views/': {
      id: '/_app/$organization/views/'
      path: '/$organization/views'
      fullPath: '/$organization/views'
      preLoaderRoute: typeof AppOrganizationViewsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/$organization/projects/': {
      id: '/_app/$organization/projects/'
      path: '/$organization/projects'
      fullPath: '/$organization/projects'
      preLoaderRoute: typeof AppOrganizationProjectsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/$organization/views/issues': {
      id: '/_app/$organization/views/issues'
      path: '/$organization/views/issues'
      fullPath: '/$organization/views/issues'
      preLoaderRoute: typeof AppOrganizationViewsIssuesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/$organization/projects/all': {
      id: '/_app/$organization/projects/all'
      path: '/$organization/projects/all'
      fullPath: '/$organization/projects/all'
      preLoaderRoute: typeof AppOrganizationProjectsAllRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppOrganizationInboxRoute: typeof AppOrganizationInboxRoute
  AppOrganizationIssuesRoute: typeof AppOrganizationIssuesRoute
  AppOrganizationNewTeamRoute: typeof AppOrganizationNewTeamRoute
  AppOrganizationIndexRoute: typeof AppOrganizationIndexRoute
  AppOrganizationProjectsAllRoute: typeof AppOrganizationProjectsAllRoute
  AppOrganizationViewsIssuesRoute: typeof AppOrganizationViewsIssuesRoute
  AppOrganizationProjectsIndexRoute: typeof AppOrganizationProjectsIndexRoute
  AppOrganizationViewsIndexRoute: typeof AppOrganizationViewsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppOrganizationInboxRoute: AppOrganizationInboxRoute,
  AppOrganizationIssuesRoute: AppOrganizationIssuesRoute,
  AppOrganizationNewTeamRoute: AppOrganizationNewTeamRoute,
  AppOrganizationIndexRoute: AppOrganizationIndexRoute,
  AppOrganizationProjectsAllRoute: AppOrganizationProjectsAllRoute,
  AppOrganizationViewsIssuesRoute: AppOrganizationViewsIssuesRoute,
  AppOrganizationProjectsIndexRoute: AppOrganizationProjectsIndexRoute,
  AppOrganizationViewsIndexRoute: AppOrganizationViewsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface PostsRouteRouteChildren {
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

const PostsRouteRouteChildren: PostsRouteRouteChildren = {
  PostsPostIdRoute: PostsPostIdRoute,
  PostsIndexRoute: PostsIndexRoute,
}

const PostsRouteRouteWithChildren = PostsRouteRoute._addFileChildren(
  PostsRouteRouteChildren,
)

interface UsersRouteRouteChildren {
  UsersUserIdRoute: typeof UsersUserIdRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

const UsersRouteRouteChildren: UsersRouteRouteChildren = {
  UsersUserIdRoute: UsersUserIdRoute,
  UsersIndexRoute: UsersIndexRoute,
}

const UsersRouteRouteWithChildren = UsersRouteRoute._addFileChildren(
  UsersRouteRouteChildren,
)

interface PathlessLayoutNestedLayoutRouteChildren {
  PathlessLayoutNestedLayoutRouteARoute: typeof PathlessLayoutNestedLayoutRouteARoute
  PathlessLayoutNestedLayoutRouteBRoute: typeof PathlessLayoutNestedLayoutRouteBRoute
}

const PathlessLayoutNestedLayoutRouteChildren: PathlessLayoutNestedLayoutRouteChildren =
  {
    PathlessLayoutNestedLayoutRouteARoute:
      PathlessLayoutNestedLayoutRouteARoute,
    PathlessLayoutNestedLayoutRouteBRoute:
      PathlessLayoutNestedLayoutRouteBRoute,
  }

const PathlessLayoutNestedLayoutRouteWithChildren =
  PathlessLayoutNestedLayoutRoute._addFileChildren(
    PathlessLayoutNestedLayoutRouteChildren,
  )

interface PathlessLayoutRouteChildren {
  PathlessLayoutNestedLayoutRoute: typeof PathlessLayoutNestedLayoutRouteWithChildren
}

const PathlessLayoutRouteChildren: PathlessLayoutRouteChildren = {
  PathlessLayoutNestedLayoutRoute: PathlessLayoutNestedLayoutRouteWithChildren,
}

const PathlessLayoutRouteWithChildren = PathlessLayoutRoute._addFileChildren(
  PathlessLayoutRouteChildren,
)

interface ApiUsersRouteChildren {
  ApiUsersIdRoute: typeof ApiUsersIdRoute
}

const ApiUsersRouteChildren: ApiUsersRouteChildren = {
  ApiUsersIdRoute: ApiUsersIdRoute,
}

const ApiUsersRouteWithChildren = ApiUsersRoute._addFileChildren(
  ApiUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  PostsRouteRoute: PostsRouteRouteWithChildren,
  UsersRouteRoute: UsersRouteRouteWithChildren,
  PathlessLayoutRoute: PathlessLayoutRouteWithChildren,
  DeferredRoute: DeferredRoute,
  JoinRoute: JoinRoute,
  RedirectRoute: RedirectRoute,
  AuthLoginRouteRoute: AuthLoginRouteRoute,
  ApiUsersRoute: ApiUsersRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  PostsPostIdDeepRoute: PostsPostIdDeepRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
