/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JoinRouteImport } from './routes/join'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as AuthLoginRouteRouteImport } from './routes/_auth/login/route'
import { Route as AppOrganizationIndexRouteImport } from './routes/_app/$organization/index'
import { Route as ApiUsersIdRouteImport } from './routes/api/users.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppOrganizationNewTeamRouteImport } from './routes/_app/$organization/new-team'
import { Route as AppOrganizationIssuesRouteImport } from './routes/_app/$organization/issues'
import { Route as AppOrganizationInboxRouteImport } from './routes/_app/$organization/inbox'
import { Route as AppOrganizationViewsIndexRouteImport } from './routes/_app/$organization/views/index'
import { Route as AppOrganizationProjectsIndexRouteImport } from './routes/_app/$organization/projects/index'
import { Route as AppOrganizationViewsIssuesRouteImport } from './routes/_app/$organization/views/issues'
import { Route as AppOrganizationProjectsAllRouteImport } from './routes/_app/$organization/projects/all'

const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRouteRoute = AuthLoginRouteRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrganizationIndexRoute = AppOrganizationIndexRouteImport.update({
  id: '/$organization/',
  path: '/$organization/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiUsersIdRoute = ApiUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiUsersRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrganizationNewTeamRoute = AppOrganizationNewTeamRouteImport.update({
  id: '/$organization/new-team',
  path: '/$organization/new-team',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrganizationIssuesRoute = AppOrganizationIssuesRouteImport.update({
  id: '/$organization/issues',
  path: '/$organization/issues',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrganizationInboxRoute = AppOrganizationInboxRouteImport.update({
  id: '/$organization/inbox',
  path: '/$organization/inbox',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrganizationViewsIndexRoute =
  AppOrganizationViewsIndexRouteImport.update({
    id: '/$organization/views/',
    path: '/$organization/views/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppOrganizationProjectsIndexRoute =
  AppOrganizationProjectsIndexRouteImport.update({
    id: '/$organization/projects/',
    path: '/$organization/projects/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppOrganizationViewsIssuesRoute =
  AppOrganizationViewsIssuesRouteImport.update({
    id: '/$organization/views/issues',
    path: '/$organization/views/issues',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppOrganizationProjectsAllRoute =
  AppOrganizationProjectsAllRouteImport.update({
    id: '/$organization/projects/all',
    path: '/$organization/projects/all',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/join': typeof JoinRoute
  '/login': typeof AuthLoginRouteRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/': typeof AppIndexRoute
  '/$organization/inbox': typeof AppOrganizationInboxRoute
  '/$organization/issues': typeof AppOrganizationIssuesRoute
  '/$organization/new-team': typeof AppOrganizationNewTeamRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/$organization': typeof AppOrganizationIndexRoute
  '/$organization/projects/all': typeof AppOrganizationProjectsAllRoute
  '/$organization/views/issues': typeof AppOrganizationViewsIssuesRoute
  '/$organization/projects': typeof AppOrganizationProjectsIndexRoute
  '/$organization/views': typeof AppOrganizationViewsIndexRoute
}
export interface FileRoutesByTo {
  '/join': typeof JoinRoute
  '/login': typeof AuthLoginRouteRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/': typeof AppIndexRoute
  '/$organization/inbox': typeof AppOrganizationInboxRoute
  '/$organization/issues': typeof AppOrganizationIssuesRoute
  '/$organization/new-team': typeof AppOrganizationNewTeamRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/$organization': typeof AppOrganizationIndexRoute
  '/$organization/projects/all': typeof AppOrganizationProjectsAllRoute
  '/$organization/views/issues': typeof AppOrganizationViewsIssuesRoute
  '/$organization/projects': typeof AppOrganizationProjectsIndexRoute
  '/$organization/views': typeof AppOrganizationViewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/join': typeof JoinRoute
  '/_auth/login': typeof AuthLoginRouteRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/$organization/inbox': typeof AppOrganizationInboxRoute
  '/_app/$organization/issues': typeof AppOrganizationIssuesRoute
  '/_app/$organization/new-team': typeof AppOrganizationNewTeamRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/_app/$organization/': typeof AppOrganizationIndexRoute
  '/_app/$organization/projects/all': typeof AppOrganizationProjectsAllRoute
  '/_app/$organization/views/issues': typeof AppOrganizationViewsIssuesRoute
  '/_app/$organization/projects/': typeof AppOrganizationProjectsIndexRoute
  '/_app/$organization/views/': typeof AppOrganizationViewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/join'
    | '/login'
    | '/api/users'
    | '/'
    | '/$organization/inbox'
    | '/$organization/issues'
    | '/$organization/new-team'
    | '/api/auth/$'
    | '/api/users/$id'
    | '/$organization'
    | '/$organization/projects/all'
    | '/$organization/views/issues'
    | '/$organization/projects'
    | '/$organization/views'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/join'
    | '/login'
    | '/api/users'
    | '/'
    | '/$organization/inbox'
    | '/$organization/issues'
    | '/$organization/new-team'
    | '/api/auth/$'
    | '/api/users/$id'
    | '/$organization'
    | '/$organization/projects/all'
    | '/$organization/views/issues'
    | '/$organization/projects'
    | '/$organization/views'
  id:
    | '__root__'
    | '/_app'
    | '/join'
    | '/_auth/login'
    | '/api/users'
    | '/_app/'
    | '/_app/$organization/inbox'
    | '/_app/$organization/issues'
    | '/_app/$organization/new-team'
    | '/api/auth/$'
    | '/api/users/$id'
    | '/_app/$organization/'
    | '/_app/$organization/projects/all'
    | '/_app/$organization/views/issues'
    | '/_app/$organization/projects/'
    | '/_app/$organization/views/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  JoinRoute: typeof JoinRoute
  AuthLoginRouteRoute: typeof AuthLoginRouteRoute
  ApiUsersRoute: typeof ApiUsersRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$organization/': {
      id: '/_app/$organization/'
      path: '/$organization'
      fullPath: '/$organization'
      preLoaderRoute: typeof AppOrganizationIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/users/$id': {
      id: '/api/users/$id'
      path: '/$id'
      fullPath: '/api/users/$id'
      preLoaderRoute: typeof ApiUsersIdRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$organization/new-team': {
      id: '/_app/$organization/new-team'
      path: '/$organization/new-team'
      fullPath: '/$organization/new-team'
      preLoaderRoute: typeof AppOrganizationNewTeamRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/$organization/issues': {
      id: '/_app/$organization/issues'
      path: '/$organization/issues'
      fullPath: '/$organization/issues'
      preLoaderRoute: typeof AppOrganizationIssuesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/$organization/inbox': {
      id: '/_app/$organization/inbox'
      path: '/$organization/inbox'
      fullPath: '/$organization/inbox'
      preLoaderRoute: typeof AppOrganizationInboxRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/$organization/views/': {
      id: '/_app/$organization/views/'
      path: '/$organization/views'
      fullPath: '/$organization/views'
      preLoaderRoute: typeof AppOrganizationViewsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/$organization/projects/': {
      id: '/_app/$organization/projects/'
      path: '/$organization/projects'
      fullPath: '/$organization/projects'
      preLoaderRoute: typeof AppOrganizationProjectsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/$organization/views/issues': {
      id: '/_app/$organization/views/issues'
      path: '/$organization/views/issues'
      fullPath: '/$organization/views/issues'
      preLoaderRoute: typeof AppOrganizationViewsIssuesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/$organization/projects/all': {
      id: '/_app/$organization/projects/all'
      path: '/$organization/projects/all'
      fullPath: '/$organization/projects/all'
      preLoaderRoute: typeof AppOrganizationProjectsAllRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppOrganizationInboxRoute: typeof AppOrganizationInboxRoute
  AppOrganizationIssuesRoute: typeof AppOrganizationIssuesRoute
  AppOrganizationNewTeamRoute: typeof AppOrganizationNewTeamRoute
  AppOrganizationIndexRoute: typeof AppOrganizationIndexRoute
  AppOrganizationProjectsAllRoute: typeof AppOrganizationProjectsAllRoute
  AppOrganizationViewsIssuesRoute: typeof AppOrganizationViewsIssuesRoute
  AppOrganizationProjectsIndexRoute: typeof AppOrganizationProjectsIndexRoute
  AppOrganizationViewsIndexRoute: typeof AppOrganizationViewsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppOrganizationInboxRoute: AppOrganizationInboxRoute,
  AppOrganizationIssuesRoute: AppOrganizationIssuesRoute,
  AppOrganizationNewTeamRoute: AppOrganizationNewTeamRoute,
  AppOrganizationIndexRoute: AppOrganizationIndexRoute,
  AppOrganizationProjectsAllRoute: AppOrganizationProjectsAllRoute,
  AppOrganizationViewsIssuesRoute: AppOrganizationViewsIssuesRoute,
  AppOrganizationProjectsIndexRoute: AppOrganizationProjectsIndexRoute,
  AppOrganizationViewsIndexRoute: AppOrganizationViewsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface ApiUsersRouteChildren {
  ApiUsersIdRoute: typeof ApiUsersIdRoute
}

const ApiUsersRouteChildren: ApiUsersRouteChildren = {
  ApiUsersIdRoute: ApiUsersIdRoute,
}

const ApiUsersRouteWithChildren = ApiUsersRoute._addFileChildren(
  ApiUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  JoinRoute: JoinRoute,
  AuthLoginRouteRoute: AuthLoginRouteRoute,
  ApiUsersRoute: ApiUsersRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
